name: ddgksf2013-Rewrite-sync
on:
  schedule:
    - cron: '20 7/12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-ddgksf2013-GithubRewriteSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ddgksf2013-GithubRewriteSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ddgksf2013/Rewrite.git"
          source_branch: "master"
          destination_branch: "ddgksf2013"
          github_token: ${{ secrets.PAT }}
