name: Neurogram-R-sync
on:
  schedule:
    - cron: '20 23/12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Neurogram-R-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Neurogram-R-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Neurogram-R/Quantumult-X.git"
          source_branch: "main"
          destination_branch: "Neurogram-R"
          github_token: ${{ secrets.PAT }}
