name: nzw9314-sync
on:
  schedule:
    - cron: '00 43 */18 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-nzw9314-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync nzw9314-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/nzw9314/QuantumultX.git"
          source_branch: "master"
          destination_branch: "nzw9314"
          github_token: ${{ secrets.PAT }}
