name: VirgilClyne-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-VirgilClyne-2020scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync VirgilClyne-2020scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/VirgilClyne/iRingo.git"
          source_branch: "main"
          destination_branch: "VirgilClyne"
          github_token: ${{ secrets.PAT }}
