name: yqc007-sync
on:
  schedule:
    - cron: '25 10/12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-yqc007-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync yqc007-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yqc007/QuantumultX.git"
          source_branch: "master"
          destination_branch: "yqc007"
          github_token: ${{ secrets.PAT }}
